package com.unmsm.fisi.entity;
// Generated 18/05/2019 03:01:04 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ManPersona generated by hbm2java
 */
@Entity
@Table(name = "man_persona", catalog = "qualityeggs")
public class ManPersona implements java.io.Serializable {

	private ManPersonaId id;
	private String vnombre;
	private String vapellidoPaterno;
	private String vapellidoMaterno;
	private String vsexo;
	private String vdomicilio;
	private String vtelefonoFijo;
	private String vtelefonoCelular;
	private String vcorreo;
	private Date dfecha;
	private Date thora;
	private Set<SegUsuario> segUsuarios = new HashSet<SegUsuario>(0);
	private ManCliente manCliente;
	private ManProveedor manProveedor;
	private ManTrabajador manTrabajador;

	public ManPersona() {
	}

	public ManPersona(ManPersonaId id) {
		this.id = id;
	}

	public ManPersona(ManPersonaId id, String vnombre, String vapellidoPaterno, String vapellidoMaterno, String vsexo,
			String vdomicilio, String vtelefonoFijo, String vtelefonoCelular, String vcorreo, Date dfecha, Date thora,
			Set<SegUsuario> segUsuarios, ManCliente manCliente, ManProveedor manProveedor,
			ManTrabajador manTrabajador) {
		this.id = id;
		this.vnombre = vnombre;
		this.vapellidoPaterno = vapellidoPaterno;
		this.vapellidoMaterno = vapellidoMaterno;
		this.vsexo = vsexo;
		this.vdomicilio = vdomicilio;
		this.vtelefonoFijo = vtelefonoFijo;
		this.vtelefonoCelular = vtelefonoCelular;
		this.vcorreo = vcorreo;
		this.dfecha = dfecha;
		this.thora = thora;
		this.segUsuarios = segUsuarios;
		this.manCliente = manCliente;
		this.manProveedor = manProveedor;
		this.manTrabajador = manTrabajador;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "vtipoDocumento", column = @Column(name = "vTipoDocumento", nullable = false, length = 20)),
			@AttributeOverride(name = "vnumeroDocumento", column = @Column(name = "vNumeroDocumento", nullable = false, length = 20)) })
	public ManPersonaId getId() {
		return this.id;
	}

	public void setId(ManPersonaId id) {
		this.id = id;
	}

	@Column(name = "vNombre", length = 100)
	public String getVnombre() {
		return this.vnombre;
	}

	public void setVnombre(String vnombre) {
		this.vnombre = vnombre;
	}

	@Column(name = "vApellidoPaterno", length = 100)
	public String getVapellidoPaterno() {
		return this.vapellidoPaterno;
	}

	public void setVapellidoPaterno(String vapellidoPaterno) {
		this.vapellidoPaterno = vapellidoPaterno;
	}

	@Column(name = "vApellidoMaterno", length = 100)
	public String getVapellidoMaterno() {
		return this.vapellidoMaterno;
	}

	public void setVapellidoMaterno(String vapellidoMaterno) {
		this.vapellidoMaterno = vapellidoMaterno;
	}

	@Column(name = "vSexo", length = 20)
	public String getVsexo() {
		return this.vsexo;
	}

	public void setVsexo(String vsexo) {
		this.vsexo = vsexo;
	}

	@Column(name = "vDomicilio", length = 100)
	public String getVdomicilio() {
		return this.vdomicilio;
	}

	public void setVdomicilio(String vdomicilio) {
		this.vdomicilio = vdomicilio;
	}

	@Column(name = "vTelefonoFijo", length = 10)
	public String getVtelefonoFijo() {
		return this.vtelefonoFijo;
	}

	public void setVtelefonoFijo(String vtelefonoFijo) {
		this.vtelefonoFijo = vtelefonoFijo;
	}

	@Column(name = "vTelefonoCelular", length = 10)
	public String getVtelefonoCelular() {
		return this.vtelefonoCelular;
	}

	public void setVtelefonoCelular(String vtelefonoCelular) {
		this.vtelefonoCelular = vtelefonoCelular;
	}

	@Column(name = "vCorreo", length = 100)
	public String getVcorreo() {
		return this.vcorreo;
	}

	public void setVcorreo(String vcorreo) {
		this.vcorreo = vcorreo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dFecha", length = 10)
	public Date getDfecha() {
		return this.dfecha;
	}

	public void setDfecha(Date dfecha) {
		this.dfecha = dfecha;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "tHora", length = 8)
	public Date getThora() {
		return this.thora;
	}

	public void setThora(Date thora) {
		this.thora = thora;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "manPersona")
	public Set<SegUsuario> getSegUsuarios() {
		return this.segUsuarios;
	}

	public void setSegUsuarios(Set<SegUsuario> segUsuarios) {
		this.segUsuarios = segUsuarios;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "manPersona")
	public ManCliente getManCliente() {
		return this.manCliente;
	}

	public void setManCliente(ManCliente manCliente) {
		this.manCliente = manCliente;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "manPersona")
	public ManProveedor getManProveedor() {
		return this.manProveedor;
	}

	public void setManProveedor(ManProveedor manProveedor) {
		this.manProveedor = manProveedor;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "manPersona")
	public ManTrabajador getManTrabajador() {
		return this.manTrabajador;
	}

	public void setManTrabajador(ManTrabajador manTrabajador) {
		this.manTrabajador = manTrabajador;
	}

}
