package com.unmsm.fisi.entity;
// Generated 18/05/2019 03:01:04 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * ManProducto generated by hbm2java
 */
@Entity
@Table(name = "man_producto", catalog = "qualityeggs")
public class ManProducto implements java.io.Serializable {

	private Integer nidProducto;
	private String vnombre;
	private String vdescripcion;
	private String vtipo;
	private Integer nstock;
	private Double nprecioUnitario;
	private Set<RegPedidoCliente> regPedidoClientes = new HashSet<RegPedidoCliente>(0);

	public ManProducto() {
	}

	public ManProducto(String vnombre, String vdescripcion, String vtipo, Integer nstock, Double nprecioUnitario,
			Set<RegPedidoCliente> regPedidoClientes) {
		this.vnombre = vnombre;
		this.vdescripcion = vdescripcion;
		this.vtipo = vtipo;
		this.nstock = nstock;
		this.nprecioUnitario = nprecioUnitario;
		this.regPedidoClientes = regPedidoClientes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "nIdProducto", unique = true, nullable = false)
	public Integer getNidProducto() {
		return this.nidProducto;
	}

	public void setNidProducto(Integer nidProducto) {
		this.nidProducto = nidProducto;
	}

	@Column(name = "vNombre", length = 20)
	public String getVnombre() {
		return this.vnombre;
	}

	public void setVnombre(String vnombre) {
		this.vnombre = vnombre;
	}

	@Column(name = "vDescripcion", length = 50)
	public String getVdescripcion() {
		return this.vdescripcion;
	}

	public void setVdescripcion(String vdescripcion) {
		this.vdescripcion = vdescripcion;
	}

	@Column(name = "vTipo", length = 20)
	public String getVtipo() {
		return this.vtipo;
	}

	public void setVtipo(String vtipo) {
		this.vtipo = vtipo;
	}

	@Column(name = "nStock")
	public Integer getNstock() {
		return this.nstock;
	}

	public void setNstock(Integer nstock) {
		this.nstock = nstock;
	}

	@Column(name = "nPrecioUnitario", precision = 22, scale = 0)
	public Double getNprecioUnitario() {
		return this.nprecioUnitario;
	}

	public void setNprecioUnitario(Double nprecioUnitario) {
		this.nprecioUnitario = nprecioUnitario;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "reg_pedido_has_man_producto", catalog = "qualityeggs", joinColumns = {
			@JoinColumn(name = "man_producto_nIdProducto", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "reg_pedido_cliente_nIdPedido", nullable = false, updatable = false) })
	public Set<RegPedidoCliente> getRegPedidoClientes() {
		return this.regPedidoClientes;
	}

	public void setRegPedidoClientes(Set<RegPedidoCliente> regPedidoClientes) {
		this.regPedidoClientes = regPedidoClientes;
	}

}
