package com.unmsm.fisi.entity;
// Generated 18/05/2019 03:01:04 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * ManTrabajador generated by hbm2java
 */
@Entity
@Table(name = "man_trabajador", catalog = "qualityeggs")
public class ManTrabajador implements java.io.Serializable {

	private ManTrabajadorId id;
	private ManPersona manPersona;
	private String varea;
	private String vpuesto;
	private Set<RegPedidoTrabajador> regPedidoTrabajadors = new HashSet<RegPedidoTrabajador>(0);

	public ManTrabajador() {
	}

	public ManTrabajador(ManPersona manPersona, String varea) {
		this.manPersona = manPersona;
		this.varea = varea;
	}

	public ManTrabajador(ManPersona manPersona, String varea, String vpuesto,
			Set<RegPedidoTrabajador> regPedidoTrabajadors) {
		this.manPersona = manPersona;
		this.varea = varea;
		this.vpuesto = vpuesto;
		this.regPedidoTrabajadors = regPedidoTrabajadors;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "manPersonaVNumeroDocumento", column = @Column(name = "man_persona_vNumeroDocumento", nullable = false, length = 20)),
			@AttributeOverride(name = "manPersonaVTipoDocumento", column = @Column(name = "man_persona_vTipoDocumento", nullable = false, length = 20)) })
	public ManTrabajadorId getId() {
		return this.id;
	}

	public void setId(ManTrabajadorId id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public ManPersona getManPersona() {
		return this.manPersona;
	}

	public void setManPersona(ManPersona manPersona) {
		this.manPersona = manPersona;
	}

	@Column(name = "vArea", nullable = false, length = 50)
	public String getVarea() {
		return this.varea;
	}

	public void setVarea(String varea) {
		this.varea = varea;
	}

	@Column(name = "vPuesto", length = 50)
	public String getVpuesto() {
		return this.vpuesto;
	}

	public void setVpuesto(String vpuesto) {
		this.vpuesto = vpuesto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "manTrabajador")
	public Set<RegPedidoTrabajador> getRegPedidoTrabajadors() {
		return this.regPedidoTrabajadors;
	}

	public void setRegPedidoTrabajadors(Set<RegPedidoTrabajador> regPedidoTrabajadors) {
		this.regPedidoTrabajadors = regPedidoTrabajadors;
	}

}
