package com.unmsm.fisi.entity;
// Generated 18/05/2019 04:07:56 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MultiTabDet generated by hbm2java
 */
@Entity
@Table(name = "multi_tab_det", catalog = "qualityeggs")
public class MultiTabDet implements java.io.Serializable {

	private MultiTabDetId id;
	private MultiTabCab multiTabCab;
	private String vdescripcionCorta;
	private String vdescripcion;

	public MultiTabDet() {
	}

	public MultiTabDet(MultiTabDetId id, MultiTabCab multiTabCab) {
		this.id = id;
		this.multiTabCab = multiTabCab;
	}

	public MultiTabDet(MultiTabDetId id, MultiTabCab multiTabCab, String vdescripcionCorta, String vdescripcion) {
		this.id = id;
		this.multiTabCab = multiTabCab;
		this.vdescripcionCorta = vdescripcionCorta;
		this.vdescripcion = vdescripcion;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "nidTabla", column = @Column(name = "nIdTabla", nullable = false)),
			@AttributeOverride(name = "vidItem", column = @Column(name = "vIdItem", nullable = false, length = 50)) })
	public MultiTabDetId getId() {
		return this.id;
	}

	public void setId(MultiTabDetId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "nIdTabla", nullable = false, insertable = false, updatable = false)
	public MultiTabCab getMultiTabCab() {
		return this.multiTabCab;
	}

	public void setMultiTabCab(MultiTabCab multiTabCab) {
		this.multiTabCab = multiTabCab;
	}

	@Column(name = "vDescripcionCorta", length = 100)
	public String getVdescripcionCorta() {
		return this.vdescripcionCorta;
	}

	public void setVdescripcionCorta(String vdescripcionCorta) {
		this.vdescripcionCorta = vdescripcionCorta;
	}

	@Column(name = "vDescripcion", length = 400)
	public String getVdescripcion() {
		return this.vdescripcion;
	}

	public void setVdescripcion(String vdescripcion) {
		this.vdescripcion = vdescripcion;
	}

}
