package com.unmsm.fisi.entity;
// Generated 18/05/2019 04:07:56 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MultiTabCab generated by hbm2java
 */
@Entity
@Table(name = "multi_tab_cab", catalog = "qualityeggs")
public class MultiTabCab implements java.io.Serializable {

	private int nidTabla;
	private String vnombreTabla;
	private String vdescripcion;
	private Set<MultiTabDet> multiTabDets = new HashSet<MultiTabDet>(0);

	public MultiTabCab() {
	}

	public MultiTabCab(int nidTabla) {
		this.nidTabla = nidTabla;
	}

	public MultiTabCab(int nidTabla, String vnombreTabla, String vdescripcion, Set<MultiTabDet> multiTabDets) {
		this.nidTabla = nidTabla;
		this.vnombreTabla = vnombreTabla;
		this.vdescripcion = vdescripcion;
		this.multiTabDets = multiTabDets;
	}

	@Id

	@Column(name = "nIdTabla", unique = true, nullable = false)
	public int getNidTabla() {
		return this.nidTabla;
	}

	public void setNidTabla(int nidTabla) {
		this.nidTabla = nidTabla;
	}

	@Column(name = "vNombreTabla", length = 150)
	public String getVnombreTabla() {
		return this.vnombreTabla;
	}

	public void setVnombreTabla(String vnombreTabla) {
		this.vnombreTabla = vnombreTabla;
	}

	@Column(name = "vDescripcion", length = 500)
	public String getVdescripcion() {
		return this.vdescripcion;
	}

	public void setVdescripcion(String vdescripcion) {
		this.vdescripcion = vdescripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "multiTabCab")
	public Set<MultiTabDet> getMultiTabDets() {
		return this.multiTabDets;
	}

	public void setMultiTabDets(Set<MultiTabDet> multiTabDets) {
		this.multiTabDets = multiTabDets;
	}

}
