package com.unmsm.fisi.entity;
// Generated 18/05/2019 04:07:56 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MultiTabDetId generated by hbm2java
 */
@Embeddable
public class MultiTabDetId implements java.io.Serializable {

	private int nidTabla;
	private String vidItem;

	public MultiTabDetId() {
	}

	public MultiTabDetId(int nidTabla, String vidItem) {
		this.nidTabla = nidTabla;
		this.vidItem = vidItem;
	}

	@Column(name = "nIdTabla", nullable = false)
	public int getNidTabla() {
		return this.nidTabla;
	}

	public void setNidTabla(int nidTabla) {
		this.nidTabla = nidTabla;
	}

	@Column(name = "vIdItem", nullable = false, length = 50)
	public String getVidItem() {
		return this.vidItem;
	}

	public void setVidItem(String vidItem) {
		this.vidItem = vidItem;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MultiTabDetId))
			return false;
		MultiTabDetId castOther = (MultiTabDetId) other;

		return (this.getNidTabla() == castOther.getNidTabla())
				&& ((this.getVidItem() == castOther.getVidItem()) || (this.getVidItem() != null
						&& castOther.getVidItem() != null && this.getVidItem().equals(castOther.getVidItem())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNidTabla();
		result = 37 * result + (getVidItem() == null ? 0 : this.getVidItem().hashCode());
		return result;
	}

}
