package com.unmsm.fisi.entity;
// Generated 18/05/2019 03:01:04 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RegPedidoCliente generated by hbm2java
 */
@Entity
@Table(name = "reg_pedido_cliente", catalog = "qualityeggs")
public class RegPedidoCliente implements java.io.Serializable {

	private Integer nidPedido;
	private ManCliente manCliente;
	private Integer ncantidad;
	private Boolean vestado;
	private Date dfecha;
	private Date thora;
	private Set<RegPago> regPagos = new HashSet<RegPago>(0);
	private Set<ManProducto> manProductos = new HashSet<ManProducto>(0);

	public RegPedidoCliente() {
	}

	public RegPedidoCliente(ManCliente manCliente) {
		this.manCliente = manCliente;
	}

	public RegPedidoCliente(ManCliente manCliente, Integer ncantidad, Boolean vestado, Date dfecha, Date thora,
			Set<RegPago> regPagos, Set<ManProducto> manProductos) {
		this.manCliente = manCliente;
		this.ncantidad = ncantidad;
		this.vestado = vestado;
		this.dfecha = dfecha;
		this.thora = thora;
		this.regPagos = regPagos;
		this.manProductos = manProductos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "nIdPedido", unique = true, nullable = false)
	public Integer getNidPedido() {
		return this.nidPedido;
	}

	public void setNidPedido(Integer nidPedido) {
		this.nidPedido = nidPedido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "man_cliente_man_persona_vNumeroDocumento", referencedColumnName = "man_persona_vNumeroDocumento", nullable = false),
			@JoinColumn(name = "man_cliente_man_persona_vTipoDocumento", referencedColumnName = "man_persona_vTipoDocumento", nullable = false) })
	public ManCliente getManCliente() {
		return this.manCliente;
	}

	public void setManCliente(ManCliente manCliente) {
		this.manCliente = manCliente;
	}

	@Column(name = "nCantidad")
	public Integer getNcantidad() {
		return this.ncantidad;
	}

	public void setNcantidad(Integer ncantidad) {
		this.ncantidad = ncantidad;
	}

	@Column(name = "vEstado")
	public Boolean getVestado() {
		return this.vestado;
	}

	public void setVestado(Boolean vestado) {
		this.vestado = vestado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dFecha", length = 10)
	public Date getDfecha() {
		return this.dfecha;
	}

	public void setDfecha(Date dfecha) {
		this.dfecha = dfecha;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "tHora", length = 8)
	public Date getThora() {
		return this.thora;
	}

	public void setThora(Date thora) {
		this.thora = thora;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "regPedidoCliente")
	public Set<RegPago> getRegPagos() {
		return this.regPagos;
	}

	public void setRegPagos(Set<RegPago> regPagos) {
		this.regPagos = regPagos;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "reg_pedido_has_man_producto", catalog = "qualityeggs", joinColumns = {
			@JoinColumn(name = "reg_pedido_cliente_nIdPedido", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "man_producto_nIdProducto", nullable = false, updatable = false) })
	public Set<ManProducto> getManProductos() {
		return this.manProductos;
	}

	public void setManProductos(Set<ManProducto> manProductos) {
		this.manProductos = manProductos;
	}

}
