package com.unmsm.fisi.entity;
// Generated 18/05/2019 03:01:04 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RegPago generated by hbm2java
 */
@Entity
@Table(name = "reg_pago", catalog = "qualityeggs")
public class RegPago implements java.io.Serializable {

	private Integer nidPago;
	private RegPedidoCliente regPedidoCliente;
	private Double npagoTotal;
	private Date dfecha;
	private Date thora;

	public RegPago() {
	}

	public RegPago(RegPedidoCliente regPedidoCliente) {
		this.regPedidoCliente = regPedidoCliente;
	}

	public RegPago(RegPedidoCliente regPedidoCliente, Double npagoTotal, Date dfecha, Date thora) {
		this.regPedidoCliente = regPedidoCliente;
		this.npagoTotal = npagoTotal;
		this.dfecha = dfecha;
		this.thora = thora;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "nIdPago", unique = true, nullable = false)
	public Integer getNidPago() {
		return this.nidPago;
	}

	public void setNidPago(Integer nidPago) {
		this.nidPago = nidPago;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "reg_pedido_cliente_nIdPedido", nullable = false)
	public RegPedidoCliente getRegPedidoCliente() {
		return this.regPedidoCliente;
	}

	public void setRegPedidoCliente(RegPedidoCliente regPedidoCliente) {
		this.regPedidoCliente = regPedidoCliente;
	}

	@Column(name = "nPagoTotal", precision = 22, scale = 0)
	public Double getNpagoTotal() {
		return this.npagoTotal;
	}

	public void setNpagoTotal(Double npagoTotal) {
		this.npagoTotal = npagoTotal;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dFecha", length = 10)
	public Date getDfecha() {
		return this.dfecha;
	}

	public void setDfecha(Date dfecha) {
		this.dfecha = dfecha;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "tHora", length = 8)
	public Date getThora() {
		return this.thora;
	}

	public void setThora(Date thora) {
		this.thora = thora;
	}

}
